version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: cat-service-db
    environment:
      POSTGRES_DB: cat-service
      POSTGRES_USER: pestr
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pestr -d cat-service"]
      interval: 10s
      timeout: 5s
      retries: 5

  cat-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cat-service-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cat-service
      SPRING_DATASOURCE_USERNAME: pestr
      SPRING_DATASOURCE_PASSWORD: changeme
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres-data: